apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: podutils
  namespace: default
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: podutils
  template:
    metadata:
      labels:
        name: podutils
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      restartPolicy: Always
      containers:
      - name: podutils
        image: vikipranata/podutils:latest
        command:
        - sleep
        - "3600"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
