apiVersion: v1
kind: Pod
metadata:
  name: podutils
  namespace: default
spec:
  containers:
  - name: podutils
    image: vikipranata/podutils:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
  restartPolicy: Always
